# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/var/folders/xh/4r0mwdg93s1_1z_j5trq5l_w0000gn/T/ipykernel_23121/2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/xh/4r0mwdg93s1_1z_j5trq5l_w0000gn/T/ipykernel_23121/1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr = np.square(arr)

In [23]:
#Taking Square Roots
np.sqrt(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 5.45981500e+01, 8.10308393e+03,
       8.88611052e+06, 7.20048993e+10, 4.31123155e+15, 1.90734657e+21,
       6.23514908e+27, 1.50609731e+35])

In [29]:
np.min(arr) #same as arr.max()

np.int64(0)

In [28]:
arr.min()

np.int64(0)

In [30]:
np.sin(arr)

array([ 0.        ,  0.84147098, -0.7568025 ,  0.41211849, -0.28790332,
       -0.13235175, -0.99177885, -0.95375265,  0.92002604, -0.62988799])

In [31]:
np.log(arr)

/var/folders/xh/4r0mwdg93s1_1z_j5trq5l_w0000gn/T/ipykernel_23121/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 1.38629436, 2.19722458, 2.77258872,
       3.21887582, 3.58351894, 3.8918203 , 4.15888308, 4.39444915])

# Great Job!

That's all we need to know for now!